apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
data:
  password: cG9zdGdyZXM=
  database_uri: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzOjU0MzIvcG9zdGdyZXM=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nyu
  labels:
    app: nyu
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0%
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: nyu
  template:
    metadata:
      labels:
        app: nyu
    spec:
      imagePullSecrets:
      - name: all-icr-io
      restartPolicy: Always
      containers:
      - name: nyu
        image: us.icr.io/nyu_devops_shopcarts/shopcarts:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
          - name: DATABASE_URI
            valueFrom:
              secretKeyRef:
                name: postgres-creds
                key: database_uri
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 30
          httpGet:
            path: /health
            port: 8080
        resources:
          limits:
            cpu: "0.20"
            memory: "64Mi"
          requests:
            cpu: "0.10"        
            memory: "32Mi"
